version: '3.8'

services:
  backend:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: personal_collection_tracker_backend
    environment:
      SPRING_PROFILES_ACTIVE: "docker"
    ports:
      - "8080:8080"
    depends_on:
      - sqlDatabase
      - flyway
  sqlDatabase:
    image: mysql:9.4.0
    container_name: sql_database
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: personal_collection
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  flyway:
    image: flyway/flyway:latest
    command:
      -url=jdbc:mysql://sqlDatabase:3306/personal_collection
      -user=user
      -password=password
      -connectRetries=5
      migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    depends_on:
      - sqlDatabase

volumes:
  db_data:
